tweaked PHP to use common components

diff --git a/ct/php/Dockerfile.mutant b/ct/php/Dockerfile.mutant
--- a/ct/php/Dockerfile.mutant
+++ b/ct/php/Dockerfile.mutant
@@ -33,51 +33,39 @@ RUN cd source && \
 # scenario details
 ARG SCENARIO_NAME
 ENV SCENARIO_NAME ${SCENARIO_NAME} 
-ADD lines.txt /experiment/lines.txt
-ADD manifest.txt /experiment/manifest.txt
+
+# generate manifest [GENERIC]
 ADD mutated /experiment/mutated
+RUN mkdir preprocessed && \
+    cd mutated && \
+    find . -type f | sed -e 's#^./##' > ../preprocessed/manifest.txt
 
-# create preprocessed version of "fixed" version of mutated file
-# and find the set of passing tests
-RUN cd source && \ 
-    ./buildconf && ./configure && \
-    make EXTRA_CFLAGS="${EXTRA_CFLAGS} -save-temps" && \
-    php ./run-tests.php -p sapi/cli/php -g PASS > /experiment/tests.txt && \
-    cd /experiment && \
-    mkdir -p "fixed/$(dirname $(cat manifest.txt))" && \
-    cp  "source/$(basename --suffix .c $(cat manifest.txt)).i" \
-        "fixed/$(cat manifest.txt)" && \
-    cd source && make clean && \
+# build oracle and generate preprocessed code [GENERIC]
+RUN cd source && \
+    ./buildconf && ./configure && make EXTRA_CFLAGS="${EXTRA_CFLAGS} -save-temps=obj" && \
+    cd ../ && \
+    ./extract-preprocessed.sh fixed && \
     find . -name '*.i' -delete && \
-    find . -name '*.s' -delete
+    find . -name '*.s' -delete && \
+    (cd source && php ./run-tests.php -p sapi/cli/php -g PASS) > tests.txt && \
+    ./filter.sh tests.txt | sponge tests.txt && \
+    (cd source && make clean)
 
-# create preprocessed versions for the single mutated file and find
-# the set of failing test cases
+# inject the buggy code and find the failing test cases
 RUN cp -r mutated/* source && \
-    cd source && \
-    make clean && make EXTRA_CFLAGS="${EXTRA_CFLAGS} -save-temps" && \
-    php ./run-tests.php -p sapi/cli/php -g PASS > /experiment/passes.txt && \
-    cd /experiment && \
-    mkdir -p "preprocessed/$(dirname $(cat manifest.txt))" && \
-    cp  "source/$(basename --suffix .c $(cat manifest.txt)).i" \
-        "preprocessed/$(cat manifest.txt)" && \
-    cd source && make clean && \
+    (cd source && make clean && make EXTRA_CFLAGS="${EXTRA_CFLAGS} -save-temps=obj") && \
+    ./filter.sh tests.txt > passes.txt && \
+    ./extract-preprocessed.sh preprocessed && \
+    (cd source && make clean) && \
     find . -name '*.i' -delete && \
     find . -name '*.s' -delete
-
-# figure out the number of failing tests
-RUN grep -oPe "(?<=\[)[\w|\.|\-|\/|\d]+\.phpt(?=\] \$)" passes.txt | sponge passes.txt && \
-    grep -oPe "(?<=\[)[\w|\.|\-|\/|\d]+\.phpt(?=\] \$)" tests.txt | sponge tests.txt && \
-    diff  --new-line-format="" \
+RUN diff  --new-line-format="" \
           --unchanged-line-format="" \
-          tests.txt passes.txt > fails.txt || exit 0
+          tests.txt passes.txt > fails.txt || exit 0 && \
+    ./blacklist.sh
 
-# remove all tests that occur in the blacklist
-RUN ./blacklist.sh
-
-# create the problem.json file
-RUN mv manifest.txt preprocessed/manifest.txt && \
-    sed "s/<<POSITIVE_TESTS>>/$(wc -l passes.txt | cut -d' ' -f1)/" problem.template.json \
+# create the problem.json file [GENERIC]
+RUN sed "s/<<POSITIVE_TESTS>>/$(wc -l passes.txt | cut -d' ' -f1)/" problem.template.json \
     | sed "s/<<NEGATIVE_TESTS>>/$(wc -l fails.txt | cut -d' ' -f1)/" \
     | sed "s/<<PROGRAM_NAME>>/${PROGRAM_NAME}/" \
     | sed "s/<<SCENARIO_NAME>>/${SCENARIO_NAME}/" > problem.json && \
